config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/info", to: "static_pages#info"
  get "/scenario", to: "scenarios#index"
  get "/character", to: "characters#index"
  get "/picture", to: "pictures#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
end

app/models/picture.rb
class Picture < ApplicationRecord
end

app/models/scenario.rb
class Scenario < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
	def index
		@characters = Character.all
	end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	def index
		@pictures = Picture.all
	end
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
	def index
		@scenarios = Scenario.all
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end

	def info
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/characters/index.html.erb
<%= render "layouts/header" %>


<div class="row">
	<div class="offset-md-3 col-md-6 mt-5">	

		<div class="main_container row">

			<% @characters.each do |character| %>
				<div class="col-md-4 mb-3 px-2">
					<div class="text-center p-3 character_container">
						<!-- <img src=" <%#= "/images/#{character.image_name}" %> "> -->
						<h1><%= link_to character.title, "#", class: "character_link text-dark" %></h1>
					</div>
				</div>
			<% end %>

		</div>

	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg sticky-top">
    <div class="container">
        <%= link_to root_path, class: "nav-link" do %>
            <h5>星月夜の描き方</h5>
        <% end %>

        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <%= link_to "Info", info_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Scenario", scenario_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Character", character_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Picture", picture_path, class: "nav-link" %>
            </li>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>星月夜の描き方</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link href="https://fonts.googleapis.com/css?family=Noto+Serif+JP:200,300|Noto+Serif+SC" rel="stylesheet">
        <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    </head>

    <body class="bg-light text-dark">
        <%= yield %>
    </body>
</html>

app/views/pictures/index.html.erb
<%= render "layouts/header" %>

<div class="row">
	<div class="offset-md-3 col-md-6 mt-5">	

		<div class="main_container row">

			<% @pictures.each do |picture| %>
				<div class="col-md-4 mb-3 px-2">
					<div class="text-center p-3 picture_container">
						<%= link_to picture.image_name, "#", class: "picture_link" %>
					</div>
				</div>
			<% end %>

		</div>

	</div>
</div>

app/views/scenarios/index.html.erb
<%= render "layouts/header" %>

<div class="row">
	<div class="offset-md-3 col-md-6 mt-5">	

		<div class="main_container">

			<% @scenarios.each do |scenario| %>
				<div class="scenario_container my-5">
					<!-- <img src=" <%#= "/images/#{scenario.image_name}" %> "> -->
					<h1><%= scenario.title %></h1>
					<h5><%= scenario.description %></h5>
					<p><%= scenario.place %> /
					<%= scenario.people %> /
					<%= scenario.time %></p>
				</div>
			<% end %>

		</div>

	</div>
</div>

app/views/static_pages/home.html.erb
<div class="home">
	<%= image_tag("home.jpg", class: "home_img") %>
	<h1>星月夜の描き方</h1>
	<div id="home_link">
		<%= link_to "Info", info_path, class: "home_link" %>
		<%= link_to "Scenario", scenario_path, class: "home_link" %>
		<%= link_to "Character", character_path, class: "home_link" %>
		<%= link_to "Picture", picture_path, class: "home_link" %>
	</div>
</div>

app/views/static_pages/info.html.erb
<%= render "layouts/header" %>

<div class="row">
	<div class="offset-md-3 col-md-6 mt-5">	


		<div class="main_container">
			<%= image_tag("シャルル.png", class: "info_img") %>

			<div class="info_link mb-4">
				<h1>向坂</h1>
				<%= link_to "https://twitter.com/siesta_hh" do %>
					<i class="fab fa-twitter fa-lg mt-1"></i>
				<% end %>
			</div>

			<p>このサイトは、向坂（緋色）の作成したTRPG用シナリオ、キャラクター、イラストの備忘録です。</p>
			<p>システムは主にクトゥルフ神話TRPGを使用しています。</p>
			<p>基本的に公開する予定はありません。</p>

		</div>

	</div>
</div>